//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string HtmlListFooter {
            get {
                return ResourceManager.GetString("HtmlListFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;style&gt;
        ///			* {
        ///				font-size: 8pt;
        ///			}
        ///			pre.source {
        ///				padding: 0px;
        ///				margin: 0px;
        ///				font-family: consolas, &quot;lucida console&quot;, monospace;
        ///			}
        ///			pre.source span.comment {
        ///				color: #060;
        ///			}
        ///			pre.source span.string {
        ///				color: #900;
        ///			}
        ///			pre.source span.directive {
        ///				color: #009;
        ///			}
        ///			pre.source span.function {
        ///				color: #069;
        ///			}
        ///			pre.source span.label {
        ///				color: #663;
        ///			}
        ///			pre.source.disabled, pre.source.disabled * {
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HtmlListHeader {
            get {
                return ResourceManager.GetString("HtmlListHeader", resourceCulture);
            }
        }
    }
}
