//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z80.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Z80.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADC	A,(HL)	8E	1	NOP	1
        ///ADC	A,(IX*)	8EDD	3	ZIX	1
        ///ADC	A,(IY*)	8EFD	3	ZIX	1
        ///ADC	A,A	8F	1	NOP	1
        ///ADC	A,B	88	1	NOP	1
        ///ADC	A,C	89	1	NOP	1
        ///ADC	A,D	8A	1	NOP	1
        ///ADC	A,E	8B	1	NOP	1
        ///ADC	A,H	8C	1	NOP	1
        ///ADC	A,IXH	8CDD	2	NOP	1
        ///ADC	A,IXL	8DDD	2	NOP	1
        ///ADC	A,IYH	8CFD	2	NOP	1
        ///ADC	A,IYL	8DFD	2	NOP	1
        ///ADC	A,L	8D	1	NOP	1
        ///ADC	A,*	CE	2	NOP	1
        ///ADC	HL,BC	4AED	2	NOP	1
        ///ADC	HL,DE	5AED	2	NOP	1
        ///ADC	HL,HL	6AED	2	NOP	1
        ///ADC	HL,SP	7AED	2	NOP	1
        ///
        ///ADD	A,(HL)	86	1	NOP	1
        ///ADD	A,(IX*)	86DD	3	ZIX	1
        ///ADD	A,(IY*)	86FD	3	ZIX	1
        ///ADD	A,A	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TASM80 {
            get {
                return ResourceManager.GetString("TASM80", resourceCulture);
            }
        }
    }
}
