//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap IconBuild {
            get {
                object obj = ResourceManager.GetObject("IconBuild", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconError {
            get {
                object obj = ResourceManager.GetObject("IconError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconHelp {
            get {
                object obj = ResourceManager.GetObject("IconHelp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconMessage {
            get {
                object obj = ResourceManager.GetObject("IconMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconSound {
            get {
                object obj = ResourceManager.GetObject("IconSound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconSoundMute {
            get {
                object obj = ResourceManager.GetObject("IconSoundMute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IconWarning {
            get {
                object obj = ResourceManager.GetObject("IconWarning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;style&gt;
        ///		body {
        ///			font-family: &quot;MS Shell Dlg 2&quot;, &quot;MS Shell Dlg&quot;, sans-serif;
        ///			font-size: 8.25pt;
        ///		}
        ///		pre {
        ///			font-family: Consolas, &quot;Lucida Console&quot;, monospace;
        ///			border: 1px dotted #CCC;
        ///			padding: 2px;
        ///		}
        ///		span.comment {
        ///			color: #060;
        ///		}
        ///		span.string {
        ///			color: #900;
        ///		}
        ///		span.directive {
        ///			color: #009;
        ///		}
        ///		span.function {
        ///			color: #069;
        ///		}
        ///		span.highlighted {
        ///			background-image: url(&quot;$(UnderlineError)&quot;);
        ///			background-repeat: repeat-x;
        ///			backgrou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OutputFormatting {
            get {
                return ResourceManager.GetString("OutputFormatting", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap UnderlineError {
            get {
                object obj = ResourceManager.GetObject("UnderlineError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UnderlineWarning {
            get {
                object obj = ResourceManager.GetObject("UnderlineWarning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
