//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Help.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Help.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype&gt;
        ///&lt;html&gt;
        ///	&lt;style&gt;
        ///	body, body * {
        ///		font-family: verdana;
        ///		font-size: 8pt;
        ///	}
        ///	html, body {
        ///		padding: 0px;
        ///		margin: 0px;
        ///	}
        ///	body {
        ///		padding-left: 5px;
        ///	}
        ///	p {
        ///		padding: 0px 0px 10px 0px;
        ///		margin: 0px;
        ///	}
        ///	a:visited {
        ///		color: blue;
        ///	}
        ///	ul {
        ///		padding: 0px;
        ///		margin: 3px 0px 0px 0px;
        ///	}
        ///	li {
        ///		list-style: none;
        ///		padding: 3px 0px 3px 20px;
        ///		background-image: url(&apos;icon_error.png&apos;);
        ///		background-repeat: no-repeat;
        ///		background-position: top left;
        ///	}
        ///	li.section [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentsHtml {
            get {
                return ResourceManager.GetString("ContentsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Brass 3 Help&lt;/title&gt;
        ///	&lt;/head&gt;
        ///
        ///	&lt;frameset cols=&quot;200,*&quot;&gt;
        ///		&lt;frame src=&quot;help/contents.html&quot; name=&quot;contents&quot; target=&quot;viewer&quot;&gt;
        ///		&lt;frame name=&quot;viewer&quot;/&gt;
        ///	&lt;/frameset&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string FramesetHtml {
            get {
                return ResourceManager.GetString("FramesetHtml", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Back {
            get {
                object obj = ResourceManager.GetObject("Icon_Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_BookClosed {
            get {
                object obj = ResourceManager.GetObject("Icon_BookClosed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_BookOpen {
            get {
                object obj = ResourceManager.GetObject("Icon_BookOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Error {
            get {
                object obj = ResourceManager.GetObject("Icon_Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Forwards {
            get {
                object obj = ResourceManager.GetObject("Icon_Forwards", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_PageBlue {
            get {
                object obj = ResourceManager.GetObject("Icon_PageBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_PageCode {
            get {
                object obj = ResourceManager.GetObject("Icon_PageCode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_PageCopy {
            get {
                object obj = ResourceManager.GetObject("Icon_PageCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_PageWhiteText {
            get {
                object obj = ResourceManager.GetObject("Icon_PageWhiteText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Printer {
            get {
                object obj = ResourceManager.GetObject("Icon_Printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body, body * {
        ///	font-family: verdana;
        ///	font-size: 8pt;
        ///}
        ///p {
        ///	padding: 0px 0px 10px 0px;
        ///	margin: 0px;
        ///}
        ///ul {
        ///	margin: 0px 0px 0px 20px;
        ///	padding: 0px;
        ///}
        ///h1, h2 {
        ///	margin: 0px;
        ///	padding: 6px 0px;
        ///}
        ///html, body {
        ///	padding: 0px;
        ///	margin: 0px;
        ///	background-color: white;
        ///}
        ///div.header {
        ///	background-color: #D4DFFF;
        ///	border-bottom: 1px solid #C8CDDE;
        ///	padding: 2px 8px;
        ///}
        ///div.header p.plugincollection {
        ///	font-size: 7pt;
        ///	color: #039;
        ///	padding-top: 6px;
        ///	padding-bottom: 2px;
        ///}
        ///div.heade [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewerCss {
            get {
                return ResourceManager.GetString("ViewerCss", resourceCulture);
            }
        }
    }
}
